### ISSUE TITLE
Improve contact us page

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geodata-mart#113]
# Problem
https://data.kartoza.com/en/vendor/contact/

![image](https://github.com/kartoza/geodata-mart/assets/2510900/c15bb4ed-65ff-4824-bd1b-5edf3575ce52)

Currently, users need to log in to submit feedback. Considering that we will have a public project to showcase the functionality, we need to enable to feedback submission for anyone visiting the platform

**Comment by seabilwe** [comment]
Reference  #95
